USE [dbCube]
GO

/****** Object:  Table [dbo].[PromoTypelkup]    Script Date: 09/02/2020 16:22:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PromoTypelkup](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[PromoTypeName] [nvarchar](50) NULL,
 CONSTRAINT [PK_PromoTypelkup] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


